version: '3.7'

networks:
  main_bridge:
    driver: bridge

services:
  web:
    build: .
    restart: always 
    ports:
      - 8000:5000
    networks:
      - main_bridge
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"